List<Map<String, dynamic>> roomsData = [
  {
    'title': 'Master Room Sea View',
    'description': 'King Bed Room with beautiful sea view',
    'capacity': '1 : 2',
    'isSelected': false,
    'imagePath': 'assets/master-sea.jpg',
    'view': 'Sea View',
    'price': 250.0,
  },
  {
    'title': 'Master Room City View',
    'description': 'King Bed Room with luxurious city view',
    'capacity': '1 : 2',
    'isSelected': false,
    'imagePath': 'assets/master-city.jpg',
    'view': 'City View',
    'price': 200.0,
  },
  {
    'title': 'Twin Room Sea View',
    'description': 'Two beds Room for two people with beautiful sea view',
    'capacity': '2',
    'isSelected': false,
    'imagePath': 'assets/twin-sea.jpg',
    'view': 'Sea View',
    'price': 200.0,
  },
  {
    'title': 'Twin Room City View',
    'description': 'Two beds Room for two people with luxurious city view',
    'capacity': '2',
    'isSelected': false,
    'imagePath': 'assets/twin-city.jpg',
    'view': 'City View',
    'price': 150.0,
  },
  {
    'title': 'Triple Room Sea View',
    'description':
        'Three beds Room for three or more people with beautiful sea view',
    'capacity': '1 : 3',
    'isSelected': false,
    'imagePath': 'assets/three-bed-sea.jpg',
    'view': 'Sea View',
    'price': 300.0,
  },
  {
    'title': 'Triple Room City View',
    'description':
        'Three beds Room for three or more people with luxurious city view',
    'capacity': '1 : 3',
    'isSelected': false,
    'imagePath': 'assets/three-bed-city.jpg',
    'view': 'City View',
    'price': 250.0,
  },
];
